/**
 * stl-writer.js — Binary STL serialization.
 *
 * Converts an array of triangles (each with 3 vertices as [x,y,z]) into
 * a binary STL ArrayBuffer that can be downloaded or loaded by Three.js.
 */

/**
 * Compute the unit normal of a triangle defined by three 3D vertices.
 * @param {number[]} v0
 * @param {number[]} v1
 * @param {number[]} v2
 * @returns {number[]} unit normal [nx, ny, nz]
 */
function triangleNormal(v0, v1, v2) {
  const ax = v1[0] - v0[0], ay = v1[1] - v0[1], az = v1[2] - v0[2];
  const bx = v2[0] - v0[0], by = v2[1] - v0[1], bz = v2[2] - v0[2];
  let nx = ay * bz - az * by;
  let ny = az * bx - ax * bz;
  let nz = ax * by - ay * bx;
  const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
  if (len === 0) return [0, 0, 1];
  return [nx / len, ny / len, nz / len];
}

/**
 * Build a binary STL file from an array of triangles.
 *
 * @param {Array<[number[], number[], number[]]>} triangles
 *   Each element is [v0, v1, v2] where each vertex is [x, y, z].
 * @returns {ArrayBuffer} Binary STL data.
 */
export function buildSTL(triangles) {
  const numTris = triangles.length;
  // Binary STL: 80-byte header + 4-byte count + 50 bytes per triangle
  const bufferSize = 80 + 4 + numTris * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // 80-byte header (zeros / ASCII text)
  const header = 'Binary STL generated by sketch2stl offline converter';
  for (let i = 0; i < 80; i++) {
    view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }

  // Triangle count
  view.setUint32(80, numTris, true);

  let offset = 84;
  for (let t = 0; t < numTris; t++) {
    const [v0, v1, v2] = triangles[t];
    const n = triangleNormal(v0, v1, v2);

    // Normal
    view.setFloat32(offset, n[0], true); offset += 4;
    view.setFloat32(offset, n[1], true); offset += 4;
    view.setFloat32(offset, n[2], true); offset += 4;

    // Vertex 0
    view.setFloat32(offset, v0[0], true); offset += 4;
    view.setFloat32(offset, v0[1], true); offset += 4;
    view.setFloat32(offset, v0[2], true); offset += 4;

    // Vertex 1
    view.setFloat32(offset, v1[0], true); offset += 4;
    view.setFloat32(offset, v1[1], true); offset += 4;
    view.setFloat32(offset, v1[2], true); offset += 4;

    // Vertex 2
    view.setFloat32(offset, v2[0], true); offset += 4;
    view.setFloat32(offset, v2[1], true); offset += 4;
    view.setFloat32(offset, v2[2], true); offset += 4;

    // Attribute byte count (unused)
    view.setUint16(offset, 0, true); offset += 2;
  }

  return buffer;
}
